name: Rust

on:
  workflow_dispatch:
    inputs:
      os:
        description: The operating system to use
        required: true
        type: string
      repository:
        description: The repository to build on
        required: true
        type: string


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
    - name: Build (Debug)
      run: 'cargo build --verbose'
    - name: Upload artifacts (Debug)
      uses: actions/upload-artifact@v4
      with:
        name: Debug build
        path: target/debug/*
    - name: Build (Release)
      run: 'cargo build --release --verbose'
    - name: Upload artifacts (Release)
      uses: actions/upload-artifact@v4
      with:
        name: Release build
        path: target/release/*
        
