name: Rust

on:
  workflow_dispatch:
    inputs:
      os:
        description: The operating system to use
        required: true
        type: string
      repository:
        description: The repository to build on
        required: true
        type: string
      profile:
        description: The profile for build
        type: choice
        options:
          - dev
          - release
          - release-lite
          - release-with-debug
        default: 'dev'
      ref:
        description: Ref a Branch/Tag/SHA whatever to checkout
        type: string


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
    - name: Cache Cargo home
      uses: actions/cache@v4
      with:
        path: |-
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: '31-cargo-home-${{ inputs.os }}-${{ inputs.repository }}-${{ inputs.ref }}-${{ hashFiles(''Cargo.lock'') }}'
        restore-keys: '31-cargo-home-${{ inputs.os }}-${{ inputs.repository }}-${{ inputs.ref }}-'
    - name: Restore cache build output
      uses: actions/cache/restore@v4
      with:
        path: |-
          ./target
          !./target/*/gn_out
          !./target/*/gn_root
          !./target/*/*.zip
          !./target/*/*.tar.gz
        key: never_saved
        restore-keys: '31-cargo-target-${{ inputs.os }}-${{ inputs.repository }}-${{ matrix.ref }}-'
    - name: Build (Debug)
      run: 'cargo build --profile ${{ inputs.profile }} --verbose'
    - name: Upload artifacts (Debug)
      uses: actions/upload-artifact@v4
      with:
        name: Debug build
        path: |
          target/debug/*
          !target/debug/gn_out
          !target/debug/build
          !target/debug/deps
          !target/debug/incremental
    - name: Build (Release)
      run: 'cargo build --release --verbose'
    - name: Upload artifacts (Release)
      uses: actions/upload-artifact@v4
      with:
        name: Release build
        path: |
          target/release/*
          !target/release/gn_out
          !target/release/build
          !target/release/deps
          !target/release/incremental
    - name: Save cache build output (main)
      uses: actions/cache/save@v4
      with:
        path: |-
          ./target
          !./target/*/gn_out
          !./target/*/gn_root
          !./target/*/*.zip
          !./target/*/*.tar.gz
        key: '31-cargo-target-${{ inputs.os }}-${{ inputs.repository }}-${{ matrix.ref }}-'
        
